const productsData = [
    {
      id:1,
      name: "Product 1",
      category: "Electronics",
      ratings: 4.5,
      price: 299.99,
      image: "https://source.unsplash.com/400x300/?electronics",
    },
    {
        id:2,
      name: "Product 2",
      category: "Clothing",
      ratings: 3.8,
      price: 49.99,
      image: "https://source.unsplash.com/400x300/?clothing",
    },
    {
        id:3,
      name: "Product 3",
      category: "Home Decor",
      ratings: 4.2,
      price: 89.99,
      image: "https://source.unsplash.com/400x300/?homedecor",
    },
    {
        id:4,
      name: "Product 4",
      category: "Kitchen Appliances",
      ratings: 4.7,
      price: 129.99,
      image: "https://source.unsplash.com/400x300/?kitchen",
    },
    {
        id:5,
      name: "Product 5",
      category: "Sports & Outdoors",
      ratings: 4.0,
      price: 79.99,
      image: "https://source.unsplash.com/400x300/?sports",
    },
    {
        id:6,
      name: "Product 6",
      category: "Furniture",
      ratings: 4.3,
      price: 199.99,
      image: "https://source.unsplash.com/400x300/?furniture",
    },
    {
        id:7,
      name: "Product 7",
      category: "Books",
      ratings: 4.8,
      price: 24.99,
      image: "https://source.unsplash.com/400x300/?books",
    },
    {
        id:8,
      name: "Product 8",
      category: "Beauty",
      ratings: 3.5,
      price: 49.99,
      image: "https://source.unsplash.com/400x300/?beauty",
    },
    {
        id:9,
      name: "Product 9",
      category: "Toys & Games",
      ratings: 4.6,
      price: 39.99,
      image: "https://source.unsplash.com/400x300/?toys",
    },
    {
        id:10,
      name: "Product 10",
      category: "Outdoor Furniture",
      ratings: 4.2,
      price: 299.99,
      image: "https://source.unsplash.com/400x300/?outdoor",
    },
];
  
export default productsData;